import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Eye, EyeOff, ImagePlus, Loader2, Pencil, Plus, Save, Trash2, X, PlayCircle } from 'lucide-react';
import { deleteGuide, getAdminGuides, saveGuide, uploadGuideImage, youtubeEmbedUrl } from '../../../services/guideApi';

const EMPTY = { title: '', slug: '', description: '', note: '', published: true, steps: [] };
const newStep = () => ({ title: '', content: '', imageUrl: '', imageAlt: '', videoUrl: '', sortOrder: 0 });
const slugify = (value) => value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export default function GuideManagement() {
  const [items, setItems] = useState([]);
  const [editing, setEditing] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const load = () => { setLoading(true); setError(''); getAdminGuides().then((data) => setItems(Array.isArray(data) ? data : data?.content || [])).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []);

  const openEditor = (guide = EMPTY) => setEditing({ ...guide, steps: (guide.steps || []).map((step) => ({ ...step })) });
  const submit = async () => {
    if (!editing.title.trim() || !editing.slug.trim()) { setError('Vui lòng nhập tiêu đề và đường dẫn.'); return; }
    if (!editing.steps.length) { setError('Hướng dẫn cần ít nhất một bước.'); return; }
    setSaving(true); setError('');
    try { await saveGuide({ ...editing, steps: editing.steps.map((step, index) => ({ ...step, sortOrder: index })) }); setEditing(null); load(); }
    catch (e) { setError(e.message); } finally { setSaving(false); }
  };
  const remove = async (guide) => { if (!window.confirm(`Xóa hướng dẫn “${guide.title}”?`)) return; try { await deleteGuide(guide.id); load(); } catch (e) { setError(e.message); } };
  const moveStep = (index, direction) => setEditing((current) => { const steps = [...current.steps]; const target = index + direction; if (target < 0 || target >= steps.length) return current; [steps[index], steps[target]] = [steps[target], steps[index]]; return { ...current, steps }; });
  const updateStep = (index, patch) => setEditing((current) => ({ ...current, steps: current.steps.map((step, i) => i === index ? { ...step, ...patch } : step) }));

  return <main className="p-4 sm:p-6 lg:p-8"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Quản lý hướng dẫn</h1><p className="mt-1 text-sm text-slate-500">Biên tập nội dung, hình Cloudinary và video YouTube hiển thị tại trang Hướng dẫn.</p></div><button type="button" onClick={() => openEditor()} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-700"><Plus className="h-4 w-4" />Thêm hướng dẫn</button></div>
    {error && <p className="mb-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="grid h-52 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-violet-500" /></div> : items.length === 0 ? <div className="py-16 text-center text-slate-400">Chưa có nội dung hướng dẫn. Hãy tạo mục đầu tiên.</div> : <div className="divide-y divide-slate-100">{items.map((guide, index) => <div key={guide.id} className="flex flex-wrap items-center gap-4 p-5 hover:bg-slate-50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-100 font-bold text-violet-700">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate font-bold text-slate-900">{guide.title}</h2><span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-semibold ${guide.published ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{guide.published ? <Eye className="h-3 w-3" /> : <EyeOff className="h-3 w-3" />}{guide.published ? 'Đã xuất bản' : 'Bản nháp'}</span></div><p className="mt-1 text-xs text-slate-400">/{guide.slug} · {guide.steps?.length || 0} bước</p></div><button type="button" onClick={() => openEditor(guide)} className="rounded-lg p-2 text-slate-400 hover:bg-violet-50 hover:text-violet-600" title="Chỉnh sửa"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => remove(guide)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" title="Xóa"><Trash2 className="h-4 w-4" /></button></div>)}</div>}</div>
    {editing && <div className="fixed inset-0 z-[100] flex justify-end bg-black/35" onMouseDown={(event) => event.target === event.currentTarget && setEditing(null)}><aside className="h-full w-full max-w-3xl overflow-y-auto bg-slate-50 shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><div><h2 className="text-lg font-bold text-slate-900">{editing.id ? 'Chỉnh sửa hướng dẫn' : 'Thêm hướng dẫn'}</h2><p className="text-xs text-slate-400">Thay đổi chỉ hiển thị công khai khi bật Xuất bản.</p></div><button type="button" onClick={() => setEditing(null)} className="rounded-full p-2 hover:bg-slate-100"><X className="h-5 w-5" /></button></header><div className="space-y-6 p-6"><section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Tiêu đề<input value={editing.title} onChange={(e) => setEditing({ ...editing, title: e.target.value, slug: editing.id ? editing.slug : slugify(e.target.value) })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-violet-500" /></label><label className="text-sm font-semibold text-slate-700">Đường dẫn<input value={editing.slug} onChange={(e) => setEditing({ ...editing, slug: slugify(e.target.value) })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-violet-500" placeholder="tao-bai-giang" /></label></div><label className="block text-sm font-semibold text-slate-700">Mô tả<textarea rows="2" value={editing.description || ''} onChange={(e) => setEditing({ ...editing, description: e.target.value })} className="mt-2 w-full resize-none rounded-xl border border-slate-200 p-3 outline-none focus:border-violet-500" /></label><label className="flex items-center gap-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={Boolean(editing.published)} onChange={(e) => setEditing({ ...editing, published: e.target.checked })} className="h-4 w-4 accent-violet-600" />Xuất bản cho người dùng</label></section>
      <div className="flex items-center justify-between"><h3 className="text-lg font-bold text-slate-900">Các bước thực hiện</h3><button type="button" onClick={() => setEditing({ ...editing, steps: [...editing.steps, { ...newStep(), sortOrder: editing.steps.length }] })} className="flex items-center gap-1 rounded-lg bg-violet-100 px-3 py-2 text-sm font-semibold text-violet-700"><Plus className="h-4 w-4" />Thêm bước</button></div>
      {editing.steps.map((step, index) => <StepEditor key={step.id || index} step={step} index={index} count={editing.steps.length} onChange={(patch) => updateStep(index, patch)} onMove={(direction) => moveStep(index, direction)} onRemove={() => setEditing({ ...editing, steps: editing.steps.filter((_, i) => i !== index) })} />)}
      <label className="block text-sm font-semibold text-slate-700">Ghi chú cuối hướng dẫn<textarea rows="2" value={editing.note || ''} onChange={(e) => setEditing({ ...editing, note: e.target.value })} className="mt-2 w-full resize-none rounded-xl border border-slate-200 p-3" /></label>{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</p>}<button type="button" disabled={saving} onClick={submit} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 py-3 font-semibold text-white hover:bg-violet-700 disabled:opacity-60">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Lưu hướng dẫn</button></div></aside></div>}
  </main>;
}

function StepEditor({ step, index, count, onChange, onMove, onRemove }) {
  const fileRef = useRef(null); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState('');
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setUploadError(''); try { onChange({ imageUrl: await uploadGuideImage(file), imageAlt: step.imageAlt || step.title }); } catch (e) { setUploadError(e.message); } finally { setUploading(false); event.target.value = ''; } };
  const validVideo = !step.videoUrl || Boolean(youtubeEmbedUrl(step.videoUrl));
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-violet-600 text-sm font-bold text-white">{index + 1}</span><b className="flex-1 text-slate-800">Bước {index + 1}</b><button disabled={index === 0} onClick={() => onMove(-1)} className="rounded p-1.5 text-slate-400 hover:bg-slate-100 disabled:opacity-20"><ArrowUp className="h-4 w-4" /></button><button disabled={index === count - 1} onClick={() => onMove(1)} className="rounded p-1.5 text-slate-400 hover:bg-slate-100 disabled:opacity-20"><ArrowDown className="h-4 w-4" /></button><button onClick={onRemove} className="rounded p-1.5 text-rose-400 hover:bg-rose-50"><Trash2 className="h-4 w-4" /></button></div><div className="space-y-4"><label className="block text-sm font-semibold text-slate-700">Tên bước<input value={step.title} onChange={(e) => onChange({ title: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5" /></label><label className="block text-sm font-semibold text-slate-700">Nội dung<textarea rows="4" value={step.content} onChange={(e) => onChange({ content: e.target.value })} className="mt-2 w-full resize-y rounded-xl border border-slate-200 p-3" /></label><div><p className="text-sm font-semibold text-slate-700">Ảnh minh họa</p><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={upload} className="hidden" /><button type="button" disabled={uploading} onClick={() => fileRef.current?.click()} className="mt-2 flex items-center gap-2 rounded-xl border border-violet-200 px-4 py-2.5 text-sm font-semibold text-violet-700 hover:bg-violet-50">{uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <ImagePlus className="h-4 w-4" />}{uploading ? 'Đang tải lên Cloudinary...' : 'Chọn ảnh từ máy'}</button>{uploadError && <p className="mt-2 text-xs text-rose-600">{uploadError}</p>}{step.imageUrl && <div className="relative mt-3 overflow-hidden rounded-xl border"><img src={step.imageUrl} alt={step.imageAlt || step.title} className="max-h-64 w-full object-contain bg-slate-50" /><button type="button" onClick={() => onChange({ imageUrl: '', imageAlt: '' })} className="absolute right-2 top-2 rounded-full bg-black/65 p-1.5 text-white"><X className="h-4 w-4" /></button></div>}</div><label className="block text-sm font-semibold text-slate-700"><span className="flex items-center gap-2"><PlayCircle className="h-4 w-4 text-red-500" />Liên kết YouTube</span><input value={step.videoUrl || ''} onChange={(e) => onChange({ videoUrl: e.target.value })} className={`mt-2 w-full rounded-xl border px-3 py-2.5 ${validVideo ? 'border-slate-200' : 'border-rose-400'}`} placeholder="https://www.youtube.com/watch?v=..." />{!validVideo && <span className="mt-1 block text-xs text-rose-600">Liên kết YouTube không hợp lệ.</span>}</label></div></section>;
}
